[package]
name = "json-path-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.210"
serde_json = "1.0.128"
serde_json_path = "0.6.7"

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "get_path"
harness = false
